
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: hks713
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace